Action=["Attainment","Starting","Neglect","Fight","Recruit","Triumph","Violate",
        "Oppose","Malice","Communicate","Persecute","Increase","Decrease","Abandon",
        "Gratify","Inquire","Antagonise","Move","Waste","Truce","Release","Befriend",
        "Judge","Desert","Dominate","Procrastinate","Praise","Separate","Take","Break",
        "Heal","Delay","Stop","Lie","Return","Immitate","Struggle","Inform","Bestow",
        "Postpone","Expose","Haggle","Imprison","Release","Celebrate","Develop",
        "Travel","Block","Harm","Debase","Overindulge","Adjourn","Adversity","Kill",
        "Disrupt","Usurp","Create","Betray","Agree","Abuse","Oppress","Inspect",
        "Ambush","Spy","Attach","Carry","Open","Carelessness","Ruin","Extravagance",
        "Trick","Arrive","Propose","Divide","Refuse","Mistrust","Deceive","Cruelty",
        "Intolerance","Trust","Excitement","Activity","Assist","Care","Negligence",
        "Passion","Work hard","Control","Attract","Failure","Pursue","Vengeance",
        "Proceedings","Dispute","Punish","Guide","Transform","Overthrow","Oppress",
        "Change"]
Subject=["Goals","Dreams","Environment","Outside","Inside","Reality","Allies",
        "Enemies","Evil","Good","Emotions","Opposition","War","Peace","The innocent",
        "Love","The spiritual","The intellectual","New ideas","Joy","Messages",
        "Energy","Balance","Tension","Friendship","The physical","A project","Pleasures",
        "Pain","Possessions","Benefits","Plans","Lies","Expectations","Legal matters",
        "Bureaucracy","Business","A path","News","Exterior factors","Advice","A plot",
        "Competition","Prison","Illness","Food","Attention","Success","Failure","Travel",
        "Jealousy","Dispute","Home","Investment","Suffering","Wishes","Tactics",
        "Stalemate","Randomness","Misfortune","Death","Disruption","Power","A burden",
        "Intrigues","Fears","Ambush","Rumor","Wounds","Extravagance","A representative",
        "Adversities","Opulence","Liberty","Military","The mundane","Trials","Masses",
        "Vehicle","Art","Victory","Dispute","Riches","Status quo","Technology","Hope",
        "Magic","Illusions","Portals","Danger","Weapons","Animals","Weather","Elements",
        "Nature","The public","Leadership","Fame","Anger","Information"]